# Generated by Django 5.0.4 on 2024-04-17 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_app', '0001_initial'),
        ('trips_app', '0003_rename_enddate_trips_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='bike_id',
            field=models.ForeignKey(db_column='bike_id', on_delete=django.db.models.deletion.CASCADE, to='motorcycle_app.bike'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
