# Generated by Django 5.0.4 on 2024-04-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0005_alter_trips_bike_id_alter_trips_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='user_id',
            new_name='user',
        ),
    ]
