# Generated by Django 5.0.4 on 2024-04-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_app', '0001_initial'),
        ('trips_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips_app.trips'),
        ),
    ]
