# Generated by Django 5.0.4 on 2024-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.AddField(
            model_name='cart',
            name='trip_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
